version: "3.8"
# Backing services: mysql, and influxdb

# volumes:
#   mysql-volume:

services:
  # mysql:
  #   # image: mysql:5.7
  #   image: mysql:8.0
  #   # volumes:
  #   #   # Just specify a path and let the Engine create a volume
  #   #   # - /var/lib/mysql
  #   #   # use a relative host path
  #   #   # - ./data/mysql:/var/lib/mysql
  #   #   # Use a defined volume
  #   #   - mysql-volume:/var/lib/mysql
  #   env_file:
  #     - ./MYSQL.env
  #   ports:
  #     - 3306:3306 # not exposed in prod ?

  # docker run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:1.7.4-pg12
  timescale:
    image: timescale/timescaledb:1.7.4-pg12
    # volumes:
    #   - ./data/timescale:/var/lib/postgresql/data
    env_file:
      - ./PG.env
    ports:
      - 5432:5432 # not exposed in prod ?

# tedflux:
#   # image: tutum/influxdb:0.10
#   image: tutum/influxdb:0.9
#   hostname: tedflux
#   environment:
#     - PRE_CREATE_DB=ted
#   ports:
#     - "8083:8083"
#     - "8086:8086"

# grafana:
#   image: grafana/grafana
#   # volumes:
#   #   - ./data/grafana/grafana.db:/var/lib/grafana/grafana.db
#   links:
#     - tedflux
#   ports:
#     - 3000:3000
